from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime
from pathlib import Path

_BROWSER_NAMES = {"chrome", "edge", "firefox"}
_ACCOUNT_COOKIE_KEYS = {
    "LOGIN_INFO", "SID", "SSID", "HSID", "__Secure-3PSID", "__Secure-1PSID",
    "SAPISID", "__Secure-3PAPISID", "__Secure-1PAPISID",
}


def parse_session_cookies(raw_text: str) -> tuple[str, dict]:
    """Parse raw cookie text (Netscape format, Cookie: header, DevTools table, or key=value pairs) into Netscape format."""
    raw = str(raw_text or "").strip()
    if not raw:
        return "", {"total_cookies": 0, "has_account_cookies": False, "account_cookie_names": [], "names": []}

    lines = [line.strip() for line in raw.splitlines() if line.strip()]
    cookies: list[dict] = []

    for line in lines:
        if line.startswith("#HttpOnly_"):
            line = line.removeprefix("#HttpOnly_")
        elif line.startswith("#"):
            continue
        if "\t" in line:
            parts = line.split("\t")
            # 1. Netscape format: domain, include_sub, path, secure, expiry, name, value
            if len(parts) >= 7 and parts[1].upper() in {"TRUE", "FALSE"} and parts[3].upper() in {"TRUE", "FALSE"}:
                domain, include_sub, path, secure, expiry, name, value = parts[:7]
                cookies.append({
                    "domain": domain, "name": name, "value": value,
                    "path": path, "secure": secure.upper() == "TRUE",
                    "expiry": int(expiry) if expiry.isdigit() else int(time.time() + 86400 * 30),
                })
            # 2. DevTools Application table: name (0), value (1), domain (2), path (3), ...
            elif len(parts) >= 2 and parts[0].lower() not in {"name", "cookie", "#"}:
                name = parts[0].strip()
                value = parts[1].strip()
                domain = parts[2].strip() if len(parts) > 2 and ("." in parts[2] or "youtube" in parts[2]) else ".youtube.com"
                if not domain.startswith("."):
                    domain = "." + domain
                path = parts[3].strip() if len(parts) > 3 and parts[3].startswith("/") else "/"
                if name and value:
                    cookies.append({
                        "domain": domain, "name": name, "value": value,
                        "path": path, "secure": True,
                        "expiry": _cookie_expiry(parts[4] if len(parts) > 4 else ""),
                    })
        elif "=" in line:
            clean = line
            curl_match = re.search(r'-(?:H|b|--header|--cookie)\s+[\'"](?:cookie:\s*)?([^\'"]+)[\'"]', clean, re.I)
            if curl_match:
                clean = curl_match.group(1)
            elif "cookie:" in clean.lower():
                clean = clean.split(":", 1)[1]
            pairs = [p.strip() for p in clean.replace("\n", ";").split(";") if "=" in p]
            expiry = int(time.time() + 86400 * 30)
            for p in pairs:
                name, _, value = p.partition("=")
                name = name.strip()
                value = value.strip().strip('"\'')
                if name and value and not name.lower().startswith("http"):
                    cookies.append({
                        "domain": ".youtube.com", "name": name, "value": value,
                        "path": "/", "secure": True, "expiry": expiry,
                    })

    netscape_lines = ["# Netscape HTTP Cookie File", "# Generated by Piano Auto Player YouTube Session Bridge", ""]
    found_account_names: list[str] = []
    for c in cookies:
        sec = "TRUE" if c["secure"] else "FALSE"
        netscape_lines.append(f"{c['domain']}\tTRUE\t{c['path']}\t{sec}\t{c['expiry']}\t{c['name']}\t{c['value']}")
        if c["name"] in _ACCOUNT_COOKIE_KEYS:
            found_account_names.append(c["name"])

    summary = {
        "total_cookies": len(cookies),
        "has_account_cookies": bool(found_account_names),
        "account_cookie_names": sorted(set(found_account_names)),
        "names": [c["name"] for c in cookies[:20]],
    }
    return "\n".join(netscape_lines), summary


def _cookie_expiry(value: str) -> int:
    text = str(value or "").strip()
    if text.isdigit():
        return int(text)
    try:
        return int(datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp())
    except (TypeError, ValueError):
        return int(time.time() + 86400 * 30)


def _legacy_session_path(root: Path) -> Path:
    return Path(root) / "data" / "youtube_session.txt"


def saved_session_path(root: Path) -> Path:
    # Authentication material must live outside the project tree so a project
    # ZIP/export cannot accidentally publish a signed-in YouTube session.
    if os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA") or (Path.home() / "AppData" / "Local"))
    else:
        base = Path(os.environ.get("XDG_STATE_HOME") or (Path.home() / ".local" / "state"))
    path = base / "PianoAutoPlayer" / "youtube_session.txt"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def load_saved_session(root: Path) -> tuple[str, dict]:
    path = saved_session_path(root)
    legacy = _legacy_session_path(root)
    if path.is_file():
        try:
            netscape, summary = parse_session_cookies(path.read_text(encoding="utf-8", errors="replace"))
            if netscape.strip():
                legacy.unlink(missing_ok=True)
                return netscape, summary
        except Exception:
            pass
    if legacy.is_file():
        try:
            netscape, summary = parse_session_cookies(legacy.read_text(encoding="utf-8", errors="replace"))
            if netscape.strip():
                save_saved_session(root, netscape)
                legacy.unlink(missing_ok=True)
                return netscape, summary
        except Exception:
            pass
    return "", {"total_cookies": 0, "has_account_cookies": False, "account_cookie_names": [], "names": []}


def save_saved_session(root: Path, netscape_text: str) -> None:
    path = saved_session_path(root)
    if netscape_text.strip():
        temp = path.with_suffix(".tmp")
        temp.write_text(netscape_text.strip() + "\n", encoding="utf-8")
        temp.replace(path)
    elif path.exists():
        path.unlink(missing_ok=True)


def saved_session_status(root: Path, summary: dict) -> dict:
    status = dict(summary or {})
    path = saved_session_path(root)
    status["persisted"] = path.is_file() and bool(status.get("total_cookies"))
    status["updated_at"] = path.stat().st_mtime if path.is_file() else 0
    return status


def clear_saved_session(root: Path) -> None:
    saved_session_path(root).unlink(missing_ok=True)
    _legacy_session_path(root).unlink(missing_ok=True)


def browser_cookie_specs(browser: str, limit: int = 6) -> list[str]:
    """Return yt-dlp browser specs, preferring recently used Windows profiles."""
    name = str(browser or "").lower().strip()
    if name not in _BROWSER_NAMES:
        return []
    specs = [name]
    if os.name != "nt":
        return specs
    profiles = _chromium_profiles(name) if name in {"chrome", "edge"} else _firefox_profiles()
    for profile in profiles[: max(0, limit - 1)]:
        spec = f"{name}:{profile}"
        if spec not in specs:
            specs.append(spec)
    return specs


def youtube_attempts(access: str, session_cookie_path: str = "") -> list[tuple[str, list[str]]]:
    """Build exact-source yt-dlp attempts for session, browser, or anonymous access."""
    mode = str(access or "auto").lower().strip()
    has_session = bool(session_cookie_path and Path(session_cookie_path).exists())

    session_attempts: list[tuple[str, list[str]]] = []
    if has_session or mode == "session":
        cookie = ["--cookies", str(session_cookie_path)]
        session_attempts = [
            ("Live YouTube session Safari-HLS", [*cookie, "--extractor-args", "youtube:player_client=web_safari", "-f", "best[protocol^=m3u8]/best"]),
            ("Live YouTube session defaults", cookie),
            ("Live YouTube session Safari-HLS + PO", [*cookie, "--extractor-args", "youtube:player_client=web_safari;fetch_pot=always", "-f", "best[protocol^=m3u8]/best"]),
        ]

    # 1. Explicit / imported session file
    if mode == "session":
        return session_attempts

    # 2. Browser cookie database specs
    if mode in _BROWSER_NAMES:
        attempts: list[tuple[str, list[str]]] = []
        for spec in browser_cookie_specs(mode):
            shown = _display_spec(spec)
            base_spec = spec == mode
            cookie = ["--cookies-from-browser", spec]
            hls_label = f"{shown} Safari-HLS session" if base_spec else f"{shown} HLS session"
            defaults_label = f"{shown} session defaults"
            po_label = f"{shown} Safari-HLS + PO session" if base_spec else f"{shown} HLS + PO session"
            attempts.append((hls_label, [*cookie, "--extractor-args", "youtube:player_client=web_safari", "-f", "best[protocol^=m3u8]/best"]))
            attempts.append((defaults_label, cookie))
            attempts.append((po_label, [*cookie, "--extractor-args", "youtube:player_client=web_safari;fetch_pot=always", "-f", "best[protocol^=m3u8]/best"]))
        return attempts

    # 3. Explicit anonymous access must never consume a saved authenticated session.
    anonymous_attempts = [
        ("current yt-dlp defaults", []),
        ("embedded fallback", ["--extractor-args", "youtube:player_client=web_embedded,default"]),
        ("mweb + PO token provider", ["--extractor-args", "youtube:player_client=mweb;fetch_pot=always"]),
        ("Safari HLS fallback", ["--extractor-args", "youtube:player_client=web_safari", "-f", "best[protocol^=m3u8]/best"]),
    ]
    if mode == "anonymous":
        return anonymous_attempts

    # 4. Automatic access prioritizes the saved live session when one exists.
    if has_session:
        return [*session_attempts, *anonymous_attempts]

    return anonymous_attempts


def browser_diagnostic(text: str, browser: str) -> str:
    """Summarize the authentication and extraction failure stages from verbose yt-dlp output."""
    raw = str(text or "")
    low = raw.lower()
    if "could not copy chrome cookie database" in low or "permission denied" in low:
        return "browser cookie database is locked; fully close the browser/background processes and retry"
    if "could not find" in low and "cookies database" in low:
        return "yt-dlp could not find that browser profile's cookie database"
    if "failed to decrypt" in low or "could not be decrypted" in low:
        match = re.search(r"Extracted\s+(\d+)\s+cookies.*?\((\d+)\s+could not be decrypted\)", raw, re.I)
        if match:
            return f"loaded {match.group(1)} cookies but {match.group(2)} could not be decrypted"
        return "some browser cookies could not be decrypted"
    if "found youtube account cookies" in low:
        if "http error 403" in low or "forbidden" in low:
            return "signed-in YouTube account cookies were detected · media request failed HTTP 403"
        return "signed-in YouTube account cookies were detected"
    match = re.search(r"Extracted\s+(\d+)\s+cookies\s+from\s+([a-z]+)", raw, re.I)
    if match:
        return f"loaded {match.group(1)} {browser} cookies, but yt-dlp did not detect signed-in YouTube account cookies"
    match_any = re.search(r"Extracted\s+(\d+)\s+cookies", raw, re.I)
    if match_any:
        return f"loaded {match_any.group(1)} {browser} cookies, but yt-dlp did not detect signed-in YouTube account cookies"
    if "extracting cookies from" in low:
        return "yt-dlp attempted to read the browser cookies but no signed-in YouTube session was confirmed"
    if "sign in to confirm you’re not a bot" in low or "sign in to confirm" in low or "bot detection" in low:
        return "bot verification challenge (Sign in to confirm you’re not a bot)"
    if "login_required" in low or "sign in" in low:
        return "LOGIN_REQUIRED / video requires signed-in session"
    if "video unavailable" in low:
        return "Video unavailable anonymously"
    return "no usable signed-in browser cookie session was confirmed"


def profile_inventory() -> dict:
    """Inspect local Windows browser profiles and check cookie lock / encryption status."""
    local = Path(os.environ.get("LOCALAPPDATA", ""))
    appdata = Path(os.environ.get("APPDATA", ""))
    results: dict[str, list[dict]] = {"chrome": [], "edge": [], "firefox": []}

    # Chrome
    chrome_root = local / "Google/Chrome/User Data"
    if chrome_root.exists():
        ls = _read_local_state(chrome_root)
        profiles_info = ls.get("profile", {}).get("info_cache", {})
        last_used = str(ls.get("profile", {}).get("last_used") or "Default")
        for p in _chromium_profiles("chrome"):
            info = profiles_info.get(p, {})
            db = chrome_root / p / "Network/Cookies"
            status = _check_db_status(db)
            results["chrome"].append({
                "profile": p,
                "name": str(info.get("name") or p),
                "user_name": str(info.get("user_name") or ""),
                "gaia_name": str(info.get("gaia_name") or ""),
                "is_signed_in": bool(info.get("gaia_id")),
                "is_last_used": p == last_used,
                "db_exists": db.exists(),
                "db_status": status,
            })

    # Edge
    edge_root = local / "Microsoft/Edge/User Data"
    if edge_root.exists():
        ls = _read_local_state(edge_root)
        profiles_info = ls.get("profile", {}).get("info_cache", {})
        last_used = str(ls.get("profile", {}).get("last_used") or "Default")
        for p in _chromium_profiles("edge"):
            info = profiles_info.get(p, {})
            db = edge_root / p / "Network/Cookies"
            status = _check_db_status(db)
            results["edge"].append({
                "profile": p,
                "name": str(info.get("name") or p),
                "user_name": str(info.get("user_name") or ""),
                "gaia_name": str(info.get("gaia_name") or ""),
                "is_signed_in": bool(info.get("gaia_id")),
                "is_last_used": p == last_used,
                "db_exists": db.exists(),
                "db_status": status,
            })

    # Firefox
    for p in _firefox_profiles():
        results["firefox"].append({
            "profile": p, "name": p, "user_name": "", "gaia_name": "",
            "is_signed_in": False, "is_last_used": False, "db_exists": True, "db_status": "readable",
        })

    return results


def _check_db_status(db_path: Path) -> str:
    if not db_path.exists():
        return "missing"
    try:
        with open(db_path, "rb"):
            pass
        return "readable (v20 App-Bound encrypted on Windows)"
    except PermissionError:
        return "locked (browser running)"
    except Exception as e:
        return f"unreadable ({e})"


def _read_local_state(root: Path) -> dict:
    try:
        return json.loads((root / "Local State").read_text(encoding="utf-8"))
    except Exception:
        return {}


def _display_spec(spec: str) -> str:
    browser, _, profile = spec.partition(":")
    base = browser.title()
    return f"{base} · {profile}" if profile else base


def _chromium_profiles(browser: str) -> list[str]:
    local = Path(os.environ.get("LOCALAPPDATA", ""))
    root = local / ("Google/Chrome/User Data" if browser == "chrome" else "Microsoft/Edge/User Data")
    if not root.exists():
        return []
    ordered: list[tuple[float, str]] = []
    preferred = _last_used_profile(root)
    for child in root.iterdir():
        if not child.is_dir() or not (child.name == "Default" or child.name.startswith("Profile ")):
            continue
        cookies = [child / "Network/Cookies", child / "Cookies"]
        existing = next((p for p in cookies if p.exists()), None)
        if not existing:
            continue
        score = existing.stat().st_mtime
        if child.name == preferred:
            score += 10_000_000_000
        ordered.append((score, child.name))
    return [name for _score, name in sorted(ordered, reverse=True)]


def _last_used_profile(root: Path) -> str:
    try:
        data = json.loads((root / "Local State").read_text(encoding="utf-8"))
        return str(data.get("profile", {}).get("last_used") or "")
    except (OSError, ValueError, TypeError):
        return ""


def _firefox_profiles() -> list[str]:
    roots = [
        Path(os.environ.get("APPDATA", "")) / "Mozilla/Firefox/Profiles",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Packages/Mozilla.Firefox_n80bbvh6b1yt2/LocalCache/Roaming/Mozilla/Firefox/Profiles",
    ]
    found: list[tuple[float, str]] = []
    for root in roots:
        if not root.exists():
            continue
        for child in root.iterdir():
            db = child / "cookies.sqlite"
            if child.is_dir() and db.exists():
                found.append((db.stat().st_mtime, child.name))
    return [name for _score, name in sorted(found, reverse=True)]

