#pragma once

#include <windows.h>
#include <wdf.h>
#include <hidport.h>

#define OMNIPAD_UMDF_VID 0x0F0F
#define OMNIPAD_UMDF_PID 0x0303
#define OMNIPAD_UMDF_VERSION 0x0100

#define OMNIPAD_KEYBOARD_REPORT_ID 0x01
#define OMNIPAD_CONTROL_REPORT_ID 0x02
#define OMNIPAD_KEYBOARD_PAYLOAD_SIZE 8
#define OMNIPAD_WATCHDOG_TIMEOUT_MS 750
#define OMNIPAD_WATCHDOG_PERIOD_MS 50

typedef UCHAR HID_REPORT_DESCRIPTOR, *PHID_REPORT_DESCRIPTOR;

#include <pshpack1.h>
typedef struct _OMNIPAD_KEYBOARD_INPUT_REPORT {
    UCHAR ReportId;
    UCHAR Modifiers;
    UCHAR Reserved;
    UCHAR Keys[6];
} OMNIPAD_KEYBOARD_INPUT_REPORT, *POMNIPAD_KEYBOARD_INPUT_REPORT;

typedef struct _OMNIPAD_CONTROL_FEATURE_REPORT {
    UCHAR ReportId;
    UCHAR Keyboard[OMNIPAD_KEYBOARD_PAYLOAD_SIZE];
} OMNIPAD_CONTROL_FEATURE_REPORT, *POMNIPAD_CONTROL_FEATURE_REPORT;
#include <poppack.h>

typedef struct _OMNIPAD_DEVICE_CONTEXT {
    WDFDEVICE Device;
    WDFQUEUE ManualQueue;
    WDFWAITLOCK StateLock;
    WDFTIMER WatchdogTimer;
    HID_DEVICE_ATTRIBUTES HidAttributes;
    HID_DESCRIPTOR HidDescriptor;
    OMNIPAD_KEYBOARD_INPUT_REPORT LastReport;
    ULONGLONG LastUpdateTick;
    BOOLEAN ReportPending;
    BOOLEAN KeyboardActive;
    UCHAR LedState;
} OMNIPAD_DEVICE_CONTEXT, *POMNIPAD_DEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(OMNIPAD_DEVICE_CONTEXT, OmniPadGetDeviceContext);

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD OmniPadEvtDeviceAdd;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL OmniPadEvtIoDeviceControl;
EVT_WDF_TIMER OmniPadEvtWatchdog;
