import assert from 'node:assert/strict';
import WebSocket from 'ws';
import { startServer } from '../helpers/server-harness.js';
import { createRoom, joinRoom, sendCommand, request } from '../helpers/http-client.js';

const PORT = 19188;
function waitForMessage(socket,predicate,timeoutMs=2000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error('WebSocket smoke timed out waiting for expected message'));},timeoutMs);const onMessage=raw=>{let payload;try{payload=JSON.parse(raw.toString());}catch{return;}if(!predicate(payload))return;cleanup();resolve(payload);};const onError=error=>{cleanup();reject(error);};const cleanup=()=>{clearTimeout(timer);socket.off('message',onMessage);socket.off('error',onError);};socket.on('message',onMessage);socket.on('error',onError);});}
export async function runRealtimeSmokes(){
  const results=[];const record=async(id,fn)=>{try{await fn();results.push({id,status:'PASS'});}catch(error){results.push({id,status:'FAIL',error:error.message});}};
  const server=await startServer({port:PORT,host:'127.0.0.1'});const baseUrl=server.baseUrl;const wsUrl=baseUrl.replace(/^http:/,'ws:')+'/ws';let hostSocket=null;
  try{
    await record('RT-01:websocket-room-join-and-initial-state',async()=>{const created=await createRoom(baseUrl,'RTROOM',{name:'RealtimeHost',roomCode:'821',accountId:'rt-host-1'});assert.equal(created.status,201);const joined=await joinRoom(baseUrl,'821',{name:'RealtimeHost',accountId:'rt-host-1'});assert.equal(joined.status,200);const memberId=joined.json.session.memberId;hostSocket=new WebSocket(wsUrl);await new Promise((resolve,reject)=>{hostSocket.once('open',resolve);hostSocket.once('error',reject);});hostSocket.send(JSON.stringify({type:'join',roomId:joined.json.session.roomId,memberId}));const initial=await waitForMessage(hostSocket,message=>message.type==='state');assert.equal(initial.transport,'websocket');assert.equal(initial.state.roomId,joined.json.session.roomId);assert.ok(Number.isFinite(Number(initial.state.serverTime)));});
    await record('RT-02:room-state-broadcast-reaches-websocket-client',async()=>{const joined=await joinRoom(baseUrl,'821',{name:'RealtimeHost',accountId:'rt-host-1'});assert.equal(joined.status,200);const memberId=joined.json.session.memberId;const roomId=joined.json.session.roomId;const responsePromise=waitForMessage(hostSocket,message=>message.type==='state'&&message.state.playback.paused===false);const playResponse=await sendCommand(baseUrl,roomId,memberId,{type:'play',position:0});assert.equal(playResponse.status,200);const update=await responsePromise;assert.equal(update.state.playback.paused,false);assert.equal(update.state.playback.ended,false);});
    await record('RT-03:room-state-revisions-are-monotonic',async()=>{const joined=await joinRoom(baseUrl,'821',{name:'RealtimeHost',accountId:'rt-host-1'});assert.equal(joined.status,200);const memberId=joined.json.session.memberId;const roomId=joined.json.session.roomId;const firstRevision=Number(joined.json.state.revision)||0;const playResponse=await sendCommand(baseUrl,roomId,memberId,{type:'play',position:0});assert.equal(playResponse.status,200);const secondRevision=Number(playResponse.json.state.revision);assert.ok(secondRevision>firstRevision);const pauseResponse=await sendCommand(baseUrl,roomId,memberId,{type:'pause',position:1});assert.equal(pauseResponse.status,200);assert.ok(Number(pauseResponse.json.state.revision)>secondRevision);});
    await record('RT-04:ping-returns-authoritative-server-time',async()=>{const joined=await joinRoom(baseUrl,'821',{name:'RealtimeHost',accountId:'rt-host-1'});assert.equal(joined.status,200);const before=Date.now();const response=await request(baseUrl,'/api/rooms/'+joined.json.session.roomId+'/ping',{method:'POST',headers:{'x-member-id':joined.json.session.memberId}});const after=Date.now();assert.equal(response.status,200);assert.ok(Number(response.json.serverTime)>=before-100);assert.ok(Number(response.json.serverTime)<=after+100);});
  }finally{hostSocket?.close();await server.stop();}
  return results;
}
