(function () {
'use strict';

const TRACKING_PARAMS = new Set(['fbclid','gclid','mc_cid','mc_eid','ref','ref_','source']);
const TITLE_SOURCE_WORDS = new Set(['wikipedia','wiki','imdb','fandom','official','site','page','homepage']);
const TOKEN_STOP = new Set(['the','a','an','of','and','or','for','to','in','on','at','by','with','from','series','page','site','official','wiki','wikipedia','imdb','fandom']);
const GENERIC_ENTITIES = new Set(['wikipedia','wikimedia foundation inc','contributors to wikimedia projects','fandom inc','youtube','github','reddit','hacker news']);
const CONFLICT_LABELS = new Set(['author','artist','status','chapters','latest_chapter','year','media_type','version','publisher']);

function text(value) { return String(value == null ? '' : value).trim(); }
function normalize(value) { return text(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim(); }
function normalizeTitle(value) { let out=normalize(value); const parts=out.split(' '); while(parts.length>1&&TITLE_SOURCE_WORDS.has(parts[parts.length-1]))parts.pop(); return parts.join(' '); }
function tokens(value) { return normalizeTitle(value).split(' ').filter(x=>x.length>1&&!TOKEN_STOP.has(x)); }
function tokenSimilarity(a,b) { const aa=new Set(tokens(a)),bb=new Set(tokens(b)); if(!aa.size||!bb.size)return 0; let overlap=0; aa.forEach(x=>{if(bb.has(x))overlap++;}); const union=new Set([...aa,...bb]).size; const minSize=Math.min(aa.size,bb.size); const jaccard=overlap/Math.max(1,union); let containment=overlap/Math.max(1,minSize); if(minSize===1&&union>1)containment*=0.55; return Math.max(jaccard,containment*0.92); }

function canonicalUrl(value) {
  const raw=text(value); if(!/^https?:\/\//i.test(raw))return'';
  try {
    const u=new URL(raw); u.hash=''; u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');
    [...u.searchParams.keys()].forEach(k=>{const low=k.toLowerCase();if(low.startsWith('utm_')||TRACKING_PARAMS.has(low))u.searchParams.delete(k);});
    if(u.pathname!=='/')u.pathname=u.pathname.replace(/\/+$/,'');
    return u.toString().replace(/\/$/,'');
  } catch (_) { return raw.replace(/\/$/,''); }
}
function hostOf(value){try{return new URL(value).hostname.toLowerCase().replace(/^www\./,'');}catch(_){return'';}}

function addAlias(set,value){if(Array.isArray(value))return value.forEach(v=>addAlias(set,v));const raw=text(value);if(!raw||/^https?:\/\//i.test(raw)||raw.length>240)return;raw.split(/\s*(?:\||;|\n)\s*/).filter(Boolean).forEach(part=>{const n=normalizeTitle(part);if(n.length>=3)set.add(n);});}
function addAliasList(set,value){if(Array.isArray(value))return value.forEach(v=>addAliasList(set,v));text(value).split(/\s*(?:,|\||;|\n)\s*/).filter(Boolean).forEach(v=>addAlias(set,v));}
function collectAliases(entry,data){const out=new Set();addAlias(out,data.identity&&data.identity.title);addAlias(out,data.search_research&&data.search_research.query);const raw=text(entry.raw||(data.input&&(data.input.raw||data.input.url)));if(raw&&!/^https?:\/\//i.test(raw))addAlias(out,raw.replace(/^\[|\]$/g,''));const sections=data.sections||{};['anime_manga','resource_details','editorial','software','video'].forEach(name=>{const section=sections[name];if(!section||typeof section!=='object')return;['title','name','series','project','repository'].forEach(k=>addAlias(out,section[k]));['alternative_titles','alternate_titles'].forEach(k=>addAliasList(out,section[k]));});return[...out];}
function collectPrimaryUrls(entry,data){const out=new Set();[entry.raw,data.fetch&&data.fetch.final_url,data.input&&data.input.url].forEach(v=>{const u=canonicalUrl(v);if(u)out.add(u);});return[...out];}
function collectReferenceUrls(data){const out=new Map();const add=(url,meta)=>{const u=canonicalUrl(url);if(u&&!out.has(u))out.set(u,meta||{});};const sr=data.search_research||{};(sr.sources||[]).forEach(s=>{const a=s&&s.analysis||{};add(s&&s.url,{role:s&&s.role?`search:${s.role}`:'search:source',title:text(a.title||s&&s.title),subjectRelevance:Number(s&&s.subject_relevance_score),queryMatch:Number(s&&s.query_match_score),curationNote:text(s&&s.curation_note)});});(((data.links||{}).important)||[]).forEach(x=>add(x&&x.url,{role:text(x&&(x.curation_role||x.relationship||'important_link')),title:text(x&&x.label),subjectRelevance:Number(x&&x.subject_relevance_score),queryMatch:Number(x&&x.query_match_score)}));return out;}
function collectEntities(data){const out=new Set();(data.entities||[]).forEach(entity=>{const n=normalize(entity&&entity.name);if(n.length>=4&&!GENERIC_ENTITIES.has(n))out.add(n);});return out;}

function canonicalLabel(label){const n=normalize(label).replace(/\s+/g,'_');if(!n)return'';if(['author','authors','written_by','writer','writers','creator','creators','created_by'].includes(n))return'author';if(['artist','artists','illustrated_by','illustrator','illustrators'].includes(n))return'artist';if(['chapter_count','chapters','chapter'].includes(n))return'chapters';if(['latest_chapter','latest_chapter_number'].includes(n))return'latest_chapter';if(['media_type','format','type'].includes(n))return'media_type';if(['genre','genres'].includes(n))return'genres';if(['published_by','publisher','studio'].includes(n))return'publisher';if(['release','release_year','year'].includes(n))return'year';if(['version','latest_version','release_version'].includes(n))return'version';if(n==='status')return'status';return'';}
function displayLabel(label){return label.split('_').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');}
function normalizeFactValue(label,value){if(value==null||typeof value==='object')return'';const raw=text(value);if(!raw||raw.length>320)return'';if(label==='chapters'||label==='latest_chapter'){const m=raw.match(/\b(\d+(?:\.\d+)?)\b/);if(m)return m[1];}if(label==='year'){const m=raw.match(/\b(19|20)\d{2}\b/);if(m)return m[0];}if(['author','artist','genres'].includes(label)){const parts=raw.split(/\s*(?:,|\||;|\/|·)\s*/).map(normalize).filter(Boolean).sort();if(parts.length)return parts.join('|');}return normalize(raw);}
function pushFact(list,label,value,support,origin){const key=canonicalLabel(label);if(!key)return;if(Array.isArray(value)){value.forEach(v=>pushFact(list,key,v,support,origin));return;}const norm=normalizeFactValue(key,value);if(!norm)return;list.push({label:key,display:text(value),norm,support:Math.max(1,Number(support)||1),origin:origin||'space'});}
function collectFacts(data){const out=[];(data.key_facts||[]).forEach(f=>pushFact(out,f&&f.label,f&&f.value,1,'key_fact'));const sections=data.sections||{};['anime_manga','resource_details','editorial','software','video'].forEach(name=>{const section=sections[name];if(!section||typeof section!=='object')return;Object.entries(section).forEach(([k,v])=>pushFact(out,k,v,1,`section:${name}`));});const sr=data.search_research||{};(sr.compiled_facts||[]).forEach(group=>{(group&&group.values||[]).forEach(v=>pushFact(out,group.label,v&&v.value,v&&v.source_count,'search_compilation'));});return out;}

function sourceScore(data,primaryUrls){const q=Math.max(0,Math.min(1,Number((data.quality||{}).extraction_score)||0));const kind=text((data.classification||{}).kind).toLowerCase();const host=hostOf(primaryUrls[0]||'');let score=q*0.55;if((data.provider_enrichment||{}).sufficient)score+=0.2;if(kind==='documentation')score+=0.12;else if(kind==='github_repository')score+=0.12;else if(kind==='web_search_research')score+=0.05;else if(kind==='article')score+=0.05;if(/\.gov$/.test(host)||/\.edu$/.test(host))score+=0.12;if(host==='wikipedia.org'||host.endsWith('.wikipedia.org'))score+=0.08;if(host==='github.com'||host.startsWith('docs.')||host.startsWith('developer.'))score+=0.08;if(/official/i.test(text((data.identity||{}).title)))score+=0.06;return Math.max(0,Math.min(1,score));}
function buildNode(entry){const data=entry.payload&&entry.payload.data||{};const primaryUrls=collectPrimaryUrls(entry,data);const aliases=collectAliases(entry,data);const title=text((data.identity||{}).title||(data.search_research||{}).query||entry.raw||primaryUrls[0]||`Space ${entry.id}`);return{id:Number(entry.id),raw:text(entry.raw),title,data,kind:text((data.classification||{}).kind||'unknown'),quality:Number((data.quality||{}).extraction_score)||0,isSearch:text((data.classification||{}).kind)==='web_search_research',aliases,primaryUrls,referenceUrls:collectReferenceUrls(data),entities:collectEntities(data),facts:collectFacts(data),summary:text(data.summary),sourceScore:sourceScore(data,primaryUrls)};}

function bestAliasSimilarity(a,b){let best=0,exact=false;a.aliases.forEach(x=>b.aliases.forEach(y=>{if(x===y&&x.length>=4){exact=true;best=1;return;}best=Math.max(best,tokenSimilarity(x,y));}));return{score:best,exact};}
function intersects(a,b){const set=new Set(a);return b.find(x=>set.has(x))||'';}
function sharedEntities(a,b){const out=[];a.entities.forEach(x=>{if(b.entities.has(x))out.push(x);});return out.slice(0,4);}
function referenceTo(source,target){for(const url of target.primaryUrls){if(source.referenceUrls.has(url))return{url,meta:source.referenceUrls.get(url)};}return null;}
function relationFor(a,b){const sameUrl=intersects(a.primaryUrls,b.primaryUrls);if(sameUrl)return{type:'duplicate_resource',confidence:1,cluster:true,reasons:[`same canonical URL: ${sameUrl}`]};const sim=bestAliasSimilarity(a,b);const aRefsB=referenceTo(a,b),bRefsA=referenceTo(b,a);const shared=sharedEntities(a,b);if(sim.exact)return{type:'same_subject',confidence:0.98,cluster:true,reasons:['exact normalized subject/title match']};if(sim.score>=0.86)return{type:'same_subject',confidence:Math.min(0.96,sim.score),cluster:true,reasons:[`strong subject-title overlap (${sim.score.toFixed(2)})`]};if(aRefsB||bRefsA){const searchRef=aRefsB&&a.isSearch?{search:a,ref:aRefsB}:{search:bRefsA&&b.isSearch?b:null,ref:bRefsA};const searchSide=searchRef.search;if(searchSide){const meta=searchRef.ref.meta||{};const refTitleSim=tokenSimilarity(searchSide.title,meta.title||'');const strongCuration=(Number.isFinite(meta.subjectRelevance)&&meta.subjectRelevance>=0.7)||(Number.isFinite(meta.queryMatch)&&meta.queryMatch>=0.78)||refTitleSim>=0.86;const compatible=sim.score>=0.56||strongCuration;const reasons=[`${searchSide.title} directly selected/referenced the other space as a source`];if(sim.score>=0.56)reasons.push(`space-title overlap ${sim.score.toFixed(2)}`);if(refTitleSim>=0.5)reasons.push(`search-result title overlap ${refTitleSim.toFixed(2)}`);if(Number.isFinite(meta.subjectRelevance))reasons.push(`search curation relevance ${meta.subjectRelevance.toFixed(2)}`);if(meta.curationNote)reasons.push(meta.curationNote);if(!compatible)reasons.push('kept outside subject cluster because subject evidence is weak');return{type:'derived_source',confidence:compatible?0.94:0.72,cluster:compatible,reasons};}return{type:'references',confidence:0.82,cluster:false,reasons:['one space directly links to the other resource']};}if(sim.score>=0.68&&shared.length)return{type:'related_subject',confidence:Math.min(0.9,(sim.score+0.78)/2),cluster:false,reasons:[`subject-title overlap ${sim.score.toFixed(2)}`,`shared entity: ${shared[0]}`]};if(shared.length>=2)return{type:'related_subject',confidence:0.74,cluster:false,reasons:[`shared entities: ${shared.slice(0,2).join(', ')}`]};return null;}

function searchWarnings(nodes){const out=[];nodes.filter(n=>n.isSearch).forEach(node=>{const sr=node.data.search_research||{},query=text(sr.query||node.title);(sr.sources||[]).forEach(source=>{if(!source||source.status==='failed')return;const analysis=source.analysis||{};const sourceTitle=text(analysis.title||source.title||source.url);const relRaw=source.subject_relevance_score;const matchRaw=source.query_match_score;const hasRel=relRaw!==undefined&&relRaw!==null&&relRaw!=='';const hasMatch=matchRaw!==undefined&&matchRaw!==null&&matchRaw!=='';const relevance=hasRel?Number(relRaw):NaN;const queryMatch=hasMatch?Number(matchRaw):tokenSimilarity(query,`${sourceTitle} ${source.url||''}`);const curationNote=text(source.curation_note);const weakRel=Number.isFinite(relevance)&&relevance<0.35;const weakMatch=Number.isFinite(queryMatch)&&queryMatch<0.35;if(weakRel||weakMatch||curationNote){out.push({spaceId:node.id,query,sourceTitle,url:text(source.url),role:text(source.curation_role||source.role||'source'),relevance:Number.isFinite(relevance)?relevance:0,queryMatch:Number.isFinite(queryMatch)?queryMatch:0,note:curationNote||'weak subject match'});}});});return out;}

function connectedClusters(nodes,edges){const parent=new Map(nodes.map(n=>[n.id,n.id]));const find=x=>{let p=parent.get(x);while(p!==parent.get(p))p=parent.get(p);let y=x;while(parent.get(y)!==p){const next=parent.get(y);parent.set(y,p);y=next;}return p;};const union=(a,b)=>{const aa=find(a),bb=find(b);if(aa!==bb)parent.set(bb,aa);};edges.filter(e=>e.cluster).forEach(e=>union(e.a,e.b));const groups=new Map();nodes.forEach(n=>{const root=find(n.id);if(!groups.has(root))groups.set(root,[]);groups.get(root).push(n);});return[...groups.values()].filter(g=>g.length>1);}
function factComparison(members){const buckets=new Map();members.forEach(node=>node.facts.forEach(f=>{if(!buckets.has(f.label))buckets.set(f.label,new Map());const values=buckets.get(f.label);if(!values.has(f.norm))values.set(f.norm,{display:f.display,support:0,spaces:new Set(),origins:new Set()});const item=values.get(f.norm);item.support+=f.support;item.spaces.add(node.id);item.origins.add(f.origin);}));const agreements=[],conflicts=[];buckets.forEach((values,label)=>{const ranked=[...values.entries()].map(([norm,v])=>({norm,...v,spaces:[...v.spaces]})).sort((a,b)=>b.support-a.support||b.spaces.length-a.spaces.length);const top=ranked[0];if(top&&(top.support>=2||top.spaces.length>=2))agreements.push({label,displayLabel:displayLabel(label),value:top.display,support:top.support,spaces:top.spaces});if(CONFLICT_LABELS.has(label)&&ranked.length>1)conflicts.push({label,displayLabel:displayLabel(label),values:ranked.slice(0,5).map(v=>({value:v.display,support:v.support,spaces:v.spaces}))});});agreements.sort((a,b)=>b.support-a.support);conflicts.sort((a,b)=>b.values.reduce((s,v)=>s+v.support,0)-a.values.reduce((s,v)=>s+v.support,0));return{agreements:agreements.slice(0,10),conflicts:conflicts.slice(0,10)};}
function clusterLabel(members){const ranked=members.slice().sort((a,b)=>b.sourceScore-a.sourceScore||b.quality-a.quality);const search=members.find(n=>n.isSearch);return(search&&search.title)||ranked[0].title;}

function analyzeWorkspace(entries){const nodes=(entries||[]).filter(e=>e&&e.status==='complete'&&e.payload&&e.payload.data).map(buildNode);const edges=[];for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const rel=relationFor(nodes[i],nodes[j]);if(rel)edges.push({a:nodes[i].id,b:nodes[j].id,...rel});}const rawClusters=connectedClusters(nodes,edges);const clusters=rawClusters.map(members=>{const comparison=factComparison(members);const ranking=members.slice().sort((a,b)=>b.sourceScore-a.sourceScore||b.quality-a.quality).map(n=>({id:n.id,title:n.title,kind:n.kind,score:n.sourceScore,quality:n.quality,url:n.primaryUrls[0]||''}));const memberIds=new Set(members.map(n=>n.id));const clusterEdges=edges.filter(e=>memberIds.has(e.a)&&memberIds.has(e.b));return{id:`cluster-${Math.min(...members.map(n=>n.id))}`,label:clusterLabel(members),members:members.map(n=>({id:n.id,title:n.title,kind:n.kind,quality:n.quality,url:n.primaryUrls[0]||''})),sourceRanking:ranking,agreements:comparison.agreements,conflicts:comparison.conflicts,relationships:clusterEdges,overview:(ranking.map(r=>members.find(n=>n.id===r.id)).find(n=>n&&n.summary&&!/^no meaningful/i.test(n.summary))||{}).summary||''};}).sort((a,b)=>b.members.length-a.members.length||a.members[0].id-b.members[0].id);const clusteredIds=new Set(clusters.flatMap(c=>c.members.map(m=>m.id)));const looseEdges=edges.filter(e=>!e.cluster);const warnings=searchWarnings(nodes);return{nodes:nodes.map(n=>({id:n.id,title:n.title,kind:n.kind,quality:n.quality,sourceScore:n.sourceScore,url:n.primaryUrls[0]||''})),edges,clusters,looseEdges,searchWarnings:warnings,standalone:nodes.filter(n=>!clusteredIds.has(n.id)).map(n=>n.id),stats:{spaces:nodes.length,clusters:clusters.length,agreements:clusters.reduce((n,c)=>n+c.agreements.length,0),conflicts:clusters.reduce((n,c)=>n+c.conflicts.length,0),relationships:edges.length,warnings:warnings.length}};}

window.BookmarkRelationships={analyzeWorkspace,canonicalUrl,normalizeTitle,tokenSimilarity};
})();
